### ISSUE TITLE
Option to add class/id to the parent wrapper div

### ISSUE THREAD

**Issue by atulmy** [ueberdosis/tiptap#1332]
**The problem I am facing**
The wrapper for the editor is a div without any class/id and is hard to style using CSS:
<img width="358" alt="Screenshot 2021-05-17 at 6 33 20 PM" src="https://user-images.githubusercontent.com/685786/118493440-bc4dc200-b73e-11eb-9ae7-ef20cb826a3d.png">

**The solution I would like**
Allow option to pass class/id to set to parent wrapper div

**Comment by philippkuehn** [comment]
You can do this already. Just add a class to your `EditorContent` component if you are using Vue or React.

**Comment by atulmy** [comment]
`EditorContent` does not seem to accept `className` or `id` as a parameter, even after ignoring, it does not apply the class.

<img width="791" alt="Screenshot 2021-05-18 at 5 33 51 PM" src="https://user-images.githubusercontent.com/685786/118647662-3776ad00-b7ff-11eb-848a-04f89603926c.png">

**Comment by philippkuehn** [comment]
ah you are right. there was an issue. should be fixed in the latest `@tiptap/react` version.

**Comment by atulmy** [comment]
Thanks!

**Comment by joejcox** [comment]
This is still an issue

![image](https://github.com/ueberdosis/tiptap/assets/26100463/35901ad3-af79-47bc-a89c-d2d6da34d6b4)

**Comment by troovi** [comment]
It's 2024 and you still don't have support for the className in EditorProvider component

**Comment by SimonTernoir** [comment]
Have you tried using `editorProps` [props](https://tiptap.dev/docs/editor/getting-started/style-editor#editor)?
```
editorProps={{
    attributes: { class: editorClassName },
}}
```

**Comment by ainahtokyandry** [comment]
We still can't add a className on the editorProvider. The following code adds classes on the editable div. 
```
editorProps={{
    attributes: { class: 'you-classNames-here },
}}
```
How can I add classes on the div who wraps all the children ? The one who wraps the menu bar and the content.
