### ISSUE TITLE
ReactNodeViewRenderer doesn't update correctly

### ISSUE THREAD

**Issue by YousefED** [ueberdosis/tiptap#1370]
I think after the update() function of a react nodeview (https://github.com/ueberdosis/tiptap/blob/0475356194623bc0f313634198de7c533d3f57d3/packages/react/src/ReactNodeViewRenderer.tsx#L107), we should check whether ContentDOMElement still has the correct parent.

The issue I'm running into is a little hard to reproduce, but it comes down to this:

- We have a custom React NodeView which renders Heading elements
- When we change the Heading level from h1 to h2, our custom NodeView nicely rerenders, but the `ContentDOM` is still a child of the h1.
- Because the ContentDOM doesn't have the correct parent, ProseMirrors setSelection logic fails

In my own project I hotfixed this with the following code:

```
export function CustomReactNodeViewRenderer(component: any, options?: any) {
  return (props: any) => {
    const renderer = ReactNodeViewRenderer(component, options)(props) as any;
    const oldUpdate = renderer.update;
    if (oldUpdate) {
      renderer.update = function () {
        let ret = oldUpdate.apply(this, arguments);
        this.contentDOM; // trigger fix
        return ret;
      };
    }
    return renderer;
  };
}
```

**Comment by YousefED** [comment]
Nevermind, might be an issue in my analysis. Will get back to it when we have a sandbox to reproduce

**Comment by philippkuehn** [comment]
Hey, hard to fix without a reproducing demo. I released a new version with the attached fix. Does that help?

**Comment by YousefED** [comment]
> Hey, hard to fix without a reproducing demo. I released a new version with the attached fix. Does that help?

Thanks! This doesn't fix it, but moving `maybeMoveContentDom` down does, i.e.:

```
this.node = node
this.decorations = decorations
this.renderer.updateProps({ node, decorations })
this.maybeMoveContentDOM()
```
