### ISSUE TITLE
Tasklist checking not working

### ISSUE THREAD

**Issue by lennardv2** [ueberdosis/tiptap#3371]
### What’s the bug you are facing?

When checking a task on the demo page https://tiptap.dev/api/nodes/task-list, it's not working and gives a console error:

```
tabindex.da7c2821.js:1 Uncaught RangeError: Index 4 out of range for <taskList(taskItem(paragraph("A list item")), taskItem(paragraph("And another one"))), paragraph("sdfsdfsadfs"), taskList(taskItem(paragraph("sdfsdfs"))), paragraph>
    at m.child (tabindex.da7c2821.js:1:6185)
    at m.findIndex (tabindex.da7c2821.js:1:6700)
    at R.nodeAt (tabindex.da7c2821.js:1:17922)
    at index.97e80bec.js:1:1540
    at tabindex.da7c2821.js:6:1492
    at Object.command (tabindex.da7c2821.js:1:1306)
    at HTMLInputElement.<anonymous> (index.97e80bec.js:1:1501)
```

### Which browser was this experienced in? Are any special extensions installed?

Chrome on OSX
Probably other browsers
iOS seems work here

### How can we reproduce the bug on our side?

Check the page in Chrome on OSX

### Can you provide a CodeSandbox?

See demo

### What did you expect to happen?

Task checked

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
It's working on my end. Could you try it again after the most recent changes we released?

**Comment by lennardv2** [comment]
Has the demo page the most recent changes included? Because it's still not working there, when checking on OSX 12.6 Chrome Versie 107.0.5304.87 m1. Tried it in incognito. Firefox works.

```
Uncaught RangeError: Index 1 out of range for <taskList(taskItem(paragraph("A list item")), taskItem(paragraph("And another one")))>
    at m.child (tabindex.da7c2821.js:1:6185)
    at m.findIndex (tabindex.da7c2821.js:1:6700)
    at R.nodeAt (tabindex.da7c2821.js:1:17922)
    at index.1017603f.js:1:1540
    at tabindex.da7c2821.js:6:1492
    at Object.command (tabindex.da7c2821.js:1:1306)
    at HTMLInputElement.<anonymous> (index.1017603f.js:1:1501)
```

**Comment by bdbch** [comment]
Thats weird. No it should have the most recent version installed. I'll investigate.

**Comment by bdbch** [comment]
Bump
