### ISSUE TITLE
Error: flushSync was called from inside a lifecycle method in <PureEditorContent>

### ISSUE THREAD

**Issue by diegoulloao** [ueberdosis/tiptap#3580]
### What’s the bug you are facing?

The component `import { EditorContent } from "@tiptap/react"` is crashing for some reason.

I'm getting the following error in console:

```
Uncaught Error: flushSync was called from inside a lifecycle method. It cannot be called when React is already rendering.
    at flushSync (react-dom.development.js:21917:1)
    at PureEditorContent.maybeFlushSync (EditorContent.tsx:82:1)
    at PureEditorContent.removeRenderer (EditorContent.tsx:100:1)
    at ReactRenderer.destroy (ReactRenderer.tsx:93:1)
    at ReactNodeView.destroy (ReactNodeViewRenderer.tsx:173:1)
...
```

More specifically here:
```
The above error occurred in the <PureEditorContent> component:
    in PureEditorContent
    in PureEditorContent (at TipTap.js:154)
    in div (at TipTap.js:145)
...
```

Reduced code:
```javascript
const TipTap = ({ editor, ...props }) => {
  return (
    <div className="tip-tap-editor-container text-editor">
      <EditorContent className="tip-tap-editor-content mt-5" editor={editor} />
    </div>
  )
}
```

If I remove the `<EditorContent>` the app doesn't crash.

Not sure if this bug is only related to our implementation.
Anyway, any help, clue or information is welcome in order to fix this issue which is urgent.

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome
Version 108.0.5359.124 (Official Build) (arm64)

macOs ventura 13.1

### How can we reproduce the bug on our side?

Not sure.

### What did you expect to happen?

Not crashing.

### Anything to add? (optional)

Tip-tap package versions:
```json
{
    "@tiptap/extension-color": "^2.0.0-beta.209",
    "@tiptap/extension-highlight": "^2.0.0-beta.209",
    "@tiptap/extension-image": "^2.0.0-beta.209",
    "@tiptap/extension-link": "^2.0.0-beta.209",
    "@tiptap/extension-placeholder": "^2.0.0-beta.209",
    "@tiptap/extension-text-style": "^2.0.0-beta.209",
    "@tiptap/extension-underline": "^2.0.0-beta.209",
    "@tiptap/react": "^2.0.0-beta.209",
    "@tiptap/starter-kit": "^2.0.0-beta.209",
}
```

React version: `16.13.1`
Node version: `v14.19.1`

You can find the entire log here: [tiptap.log](https://github.com/ueberdosis/tiptap/files/10315868/tiptap.log)

---
**Note:** my app depends of this node version only

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by HiDeoo** [comment]
I'm also experiencing the same errors after an update from `2.0.0-beta.202` to `2.0.0-beta.209`.

From a real quick search, it looks like #3331 may be the only changes related to this error between the 2 versions.

**Comment by kolyagora** [comment]
There is a PR addressing this issue: https://github.com/ueberdosis/tiptap/pull/3533

**Comment by diegoulloao** [comment]
> There is a PR addressing this issue: #3533

yeah, but it doesn't solves this one, this is coming even for previous versions than `2.0.0-beta.209`, at least for me.

**Comment by diegoulloao** [comment]
> I'm also experiencing the same errors after an update from `2.0.0-beta.202` to `2.0.0-beta.209`.
> 
> From a real quick search, it looks like #3331 may be the only changes related to this error between the 2 versions.

yeah, but it doesn't solves this one, this is coming even from previous versions than 2.0.0-beta.209, at least for me.

**Comment by diegoulloao** [comment]
I believe is pending of approval. PR #3533 should fix this issue.

**Comment by JosephHalter** [comment]
+1

**Comment by arpit016** [comment]
@bdbch I am still experiencing this bug, I am using tiptap v2.0.3. Any fix or workaround?, It mainly crashes the app when the editor is unmounting or when the user is navigating away from the page containing editor. Can we reopen this issue?

**Comment by bdbch** [comment]
Could you create a replicatable sandbox for us? @Hideman85 @arpit016 so we can verify the issue still exist?

**Comment by rbruels** [comment]
@bdbch Still occurs in 2.0.4 -- here's a code sandbox: https://codesandbox.io/s/github/rbruels/tiptap-3580-sandbox

**Comment by bdbch** [comment]
Moved back to the backlog

**Comment by benjackwhite** [comment]
For what it's worth, testing locally for us and removing the [flushSync call](https://github.com/ueberdosis/tiptap/blob/develop/packages/react/src/EditorContent.tsx#L78) all-together of course stopped the error. Interestingly though through testing a bunch of our custom Nodes and navigating across multiple dynamically re-initialised editors, nothing else seemed to be off.

I assume there is a good reason for using `flushSync` but it isn't super obvious from the code alone what that is 🤔

**Comment by Slapbox** [comment]
Fwiw I've never seen this occur over hundreds of hours building our TipTap/React editor (but mostly using `2.1.0-rc.*`.) I wonder what the cause could be.

**Comment by rbruels** [comment]
@Slapbox Feel free to check my code sandbox — see if you can reproduce too. Maybe you’ll have an idea why it’s happening

**Comment by Slapbox** [comment]
Ah I didn't realize the issue was specific to `ReactNodeViewRenderer` rather than `useEditor`/`EditorContent`. We don't use `ReactNodeViewRenderer`, so I guess that explains never seeing it.

Relink to the relevant code sandbox for convenience: https://codesandbox.io/s/github/rbruels/tiptap-3580-sandbox

**Comment by dwzkit** [comment]
I recently discovered this performance issue with React's NodeView while doing some fast input and quick line additions. The problem is becoming progressively more noticeable, leading to considerable lag that could compromise the user experience and potentially limit the application's utility for more demanding editorial tasks. I kindly bring this to your attention in the hopes that it might be an area for future optimization. Thank you for your continued efforts in developing this tool; your work is highly valued.  https://github.com/ueberdosis/tiptap/issues/4355

**Comment by dwzkit** [comment]
In my situation, I was experiencing poor performance and lag as the number of lines in a `Paragraph` node with a NodeView increased. This significantly impacted the user experience during text input. However, when I changed the `maybeFlushSync(fn: () => void)` method from:

```javascript
if (this.initialized) {
  flushSync(fn);
} else {
  fn();
}
```

to:

```javascript
if (this.initialized) {
  fn();
} else {
  fn();
}
```

The lag and performance issues were resolved. I am just not sure what potential risks this change might introduce.

**Comment by philipaarseth** [comment]
Experienced this after updating from 2.0.0-beta.220 to 2.1.7. Seems to have been caused by using setContent inside a useEffect. Moving the initialize editor content to `useEditor({ content: content` seem to have fixed it for me.

```
editor?.commands?.setContent({
  type: "doc",
  content: doc?.content || []
});
```

**Comment by essmahr** [comment]
We are running into this as well for the same reason as @philipaarseth (imperatively updating content in a `useEffect`).

Since we depend on updating content within an effect like this, I found that wrapping the offending `setContent` inside a [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask) also makes the error go away...  but watching this issue for a proper fix 😄

**Comment by Aldredcz** [comment]
FYI: We also struggled with this, but after a bump from `2.0.0-beta.209` to `2.1.13` the issue disappeared 🎉

**Comment by ccreusat** [comment]
Still experiencing the error with `2.1.13` or `2.1.16`

**Comment by emroot** [comment]
Still experiencing this on 2.2.3 :(

**Comment by semanticist21** [comment]
Putting logic inside queueMicrotask(..) solved perfectly! 
Thanks.

**Comment by fridaystreet** [comment]
still getting this in 2.3.0 being caused by ReactNodeViewRenderer 

any ideas on if this is going to be fixed or what is the workaround for when it is caused by custom node view?

Cheers

**Comment by rfdrake27** [comment]
Same here. Still not fixed in 2.30 and my console is just getting flooded in the flushSync errors.

**Comment by mhogryd** [comment]
I'm having this problem as well with 2.4.0.

**Comment by nperez0111** [comment]
Should be resolved with tiptap 2.5 since we no longer have to flushSync anymore

**Comment by Aslam97** [comment]
@nperez0111 still facing the same issue with 2.5.9

```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
```

**Comment by rfdrake27** [comment]
I can confirm it's still present on 2.5.9 as well.

**Comment by nperez0111** [comment]
You are using a React nodeview? Or is this with useEditor?

I must've read the issue incorrectly. Tiptap 2.5 fixes useEditor, node views will be resolved with: https://github.com/ueberdosis/tiptap/pull/5273

**Comment by Nantris** [comment]
I don't see this issue anymore but I do sometimes see: `Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition PureEditorContent`

I think this only occurs when swapping the editor out for a new one (eg user changes the selected content) but we're not breaking any rules of React or of TipTap as far as I can tell, so I wouldn't expect this.

**Comment by nperez0111** [comment]
PureEditorContent is to do with React nodeviews: https://github.com/ueberdosis/tiptap/blob/32ed87b409207897753c65b2e7c44c1a64d3173d/packages/react/src/EditorContent.tsx#L88-L99

So not yet resolved, but will be with https://github.com/ueberdosis/tiptap/pull/5273

**Comment by Nantris** [comment]
Ah apologies. I was pretty sure I'd seen it on a page where we used none, but I'm probably mistaken about that.

**Comment by nperez0111** [comment]
This should now be resolved with 2.6.0

**Comment by rajatkulkarni95** [comment]
@nperez0111 I think it still isn't fixed. I'm on the latest `2.6.2` patch, and here's an example.

One note has `node views` component (the purple text blocks you see), while the other doesn't. When the note loads, you can see the warning in the console, but not for the other note.

```
    "@tiptap/pm": "^2.6.2",
    "@tiptap/react": "^2.6.2",
```    

https://github.com/user-attachments/assets/c11d6c04-d759-4f1a-9308-61dd87d86970

**Comment by rajatkulkarni95** [comment]
> Given what you were doing here I would expect it to only render once. I'd be interested if you logged in the component that called useEditor whether it was re-rendering multiple times.

Here's the logs. Both cause the same amount of renders it seems.

> Do note that this is only a warning & React does the right thing anyway
Yeah till it won't have adverse side effects, I'm not really concerned.

https://github.com/user-attachments/assets/44ba6b49-3d6b-45fa-9259-21233afd83f0

**Comment by nperez0111** [comment]
> Here's the logs. Both cause the same amount of renders it seems.

That's a lot of renders... I would consider wrapping the component that renders the editor to be memoized to be shielded from all of these renders.

useEditor wherever possible will try to re-use the editor instance, but it can be garbage collected if the editors are far enough apart. If collected, this would destroy the instance & force a remount after recreating. All that to say, I would totally expect this to happen with how many times it is rendered. React does not really give us much room here for a solution. We need it to be synchronous & it isn't, we don't have a way to know whether React is already rendering something else. So our hands are tied here, but again, not an actual issue.

So I think it is safe to say, if you don't recreate the editor a bunch of times really quickly this _already is solved_. Tons of people already have this in prod from my understanding

**Comment by rajatkulkarni95** [comment]
> > Here's the logs. Both cause the same amount of renders it seems.
> 
> That's a lot of renders... I would consider wrapping the component that renders the editor to be memoized to be shielded from all of these renders.
> 
> useEditor wherever possible will try to re-use the editor instance, but it can be garbage collected if the editors are far enough apart. If collected, this would destroy the instance & force a remount after recreating. All that to say, I would totally expect this to happen with how many times it is rendered. React does not really give us much room here for a solution. We need it to be synchronous & it isn't, we don't have a way to know whether React is already rendering something else. So our hands are tied here, but again, not an actual issue.
> 
> So I think it is safe to say, if you don't recreate the editor a bunch of times really quickly this _already is solved_. Tons of people already have this in prod from my understanding

Yeah it's rendering 15 times, which seems a lot. So I have an `Editor.tsx` component that has a bunch of states and stuff, and that calls my custom `useCustomEditor` hook which calls `useEditor` from tiptap.

I think some re-renders are unavoidable, since some of the extensions require some data from state, but I feel 15 can be brought down.

Will check, thanks!

**Comment by wasauce** [comment]
We are experiencing this issue intermittently.

We are using 2.9.1

See a screenshot from the console and a video showing the issue.

![image](https://github.com/user-attachments/assets/3fe41721-29b6-4cac-a716-2ad200a85e7b)

video:

https://github.com/user-attachments/assets/c4d86df0-850d-4406-941d-ad45908cca99


@nperez0111 do you have any suggestions for what we are doing wrong?

As you can see in the video - first load, we see the error in the console but everything renders. Then on refresh, the content does not load.

We do see there are a few other issues https://github.com/ueberdosis/tiptap/issues?q=flushSync+was+called+from+inside+a+lifecycle+method but they all seem resolved and don't resolve our issue.

Thank you for any/all help and guidance!

**Comment by nperez0111** [comment]
@wasauce 
Please don't cross post. To not spam people on this thread, follow the rest of his discussion here: https://github.com/ueberdosis/tiptap/discussions/5801#discussion-7425802
