### ISSUE TITLE
[PRO]: Vercel Production Build Deployment Issue With Pro Packages

### ISSUE THREAD

**Issue by kevinlu1248** [ueberdosis/tiptap#3983]
### Which packages did you experience the bug in?

react, mathematics

### What Tiptap version are you using?

2.0.1

### What’s the bug you are facing?

I get the following error in the build logs when trying to do a production build of my app on Vercel/Next JS.

```
error An unexpected error occurred: "https://registry.tiptap.dev/@tiptap-pro%2fextension-unique-id/-/extension-unique-id-2.0.1.tgz: Request failed \"500 Internal Server Error\"".
```

I have the TIPTAP_PRO_TOKEN environment variable set. I even tried setting the install command to `yarn config set "@tiptap-pro:registry" https://registry.tiptap.dev/ && TIPTAP_PRO_TOKEN=XXX yarn install` (replacing XXX with my token) and it still didn't work. I'm wondering what I should try next.

### What browser are you using?

Chrome

### What did you expect to happen?

Building successfully.

### Anything to add? (optional)

It seems like an authentication issue and not a registry issue since otherwise I would've gotten 404 and not 500.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by kevinlu1248** [comment]
Never mind I fixed it. It's a confusing part on Vercel but the docs are here https://vercel.com/guides/using-private-dependencies-with-vercel. Instead of putting in npmrc as key-value pairs in the env var put it in directly to the NPM_RC key.

**Comment by ccreusat** [comment]
Hi @kevinlu1248 , I have the same issue with vercel.. I tried to add my npmrc file as following:

```
// .npmrc
@tiptap-pro:registry=https://registry.tiptap.dev
//registry.tiptap.dev/:_authToken=TIPTAP_PRO_TOKEN
```

then 

```
vc env add NPM_RC preview < .npmrc
```

but I still have the 500 error.. Any tip ?

**Comment by kevinlu1248** [comment]
Can you try adding this on Vercel directly rather than CLI? Not too sure, I haven't worked on the project in a while @ccreusat
