### ISSUE TITLE
[Bug]: CapsLock interferes with hotkeys (specifically undo Ctrl+Z)

### ISSUE THREAD

**Issue by Slapbox** [ueberdosis/tiptap#4055]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

Activated CapsLock prevents undo from occurring (at least on Linux, but presumably everywhere)

### What browser are you using?

Chrome

### Code example

https://tiptap.dev/api/extensions/history#usage

### What did you expect to happen?

CapsLock should never interfere with any defined hotkey

### Anything to add? (optional)

The handling of hotkeys needs to be prioritized for 2.2.0 in my humble opinion. There are a a few edge cases in the core example code that affect basic usage but probably don't require a lot of work.

Related #4006

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Slapbox** [comment]
I've created #4111 to track the related hotkey failures that affect TipTap by default.

**Comment by Slapbox** [comment]
This should be fixed by #4132

**Comment by vinzdef** [comment]
This bug is back @Nantris https://github.com/ueberdosis/tiptap/issues/5789
