### ISSUE TITLE
[Bug]: Tiptap 2.5.0-beta.3 can lead to multiple versions of prosemirror-model

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5239]
### Affected Packages

pm

### Version(s)

2.5.0-beta.3 (and possibly earlier 2.5.0-beta.x)

### Bug Description

`prosemirror-model@1.21.0` and `prosemirror-model@1.21.1` can both end up installed, which breaks a lot of thing.

### Browser Used

Chrome

### Expected Behavior

A single version of `prosemirror-model` should be installed.

### Additional Context (Optional)

```
❯ yarn why prosemirror-model
yarn why v1.22.22
[1/4] Why do we have the module "prosemirror-model"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "prosemirror-model@1.21.1"
info Has been hoisted to "prosemirror-model"
info Reasons this module exists
   - Hoisted from "prosemirror-schema-list#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-commands#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-gapcursor#prosemirror-model"
   - Hoisted from "prosemirror-schema-list#prosemirror-state#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-schema-basic#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-markdown#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-view#prosemirror-model"
   - Hoisted from "prosemirror-schema-list#prosemirror-transform#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-tables#prosemirror-model"
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
=> Found "@tiptap/pm#prosemirror-model@1.21.0"
info This module exists because "@tiptap#pm" depends on it.
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
=> Found "@tiptap/pm#prosemirror-schema-list#prosemirror-model@1.21.1"
info This module exists because "@tiptap#pm#prosemirror-schema-list" depends on it.
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Hm, I may have to revert it all together then. I found that prosemirror-model had an accidental breaking change in 1.21.1 which I reported here: https://github.com/ProseMirror/prosemirror/issues/1473

Thanks for bringing it up

**Comment by Nantris** [comment]
Ah I hadn't even realized that. The issue I hit was that having two versions of `prosemirror-model` installed led to parsing inconsistencies and a warning from ProseMirror that we probably had two versions of `prosemirror-model` installed.

Thanks for your attention on this!

**Comment by Nantris** [comment]
The exact error is:

`Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`

**Comment by Nantris** [comment]
Thanks for your ongoing great work @nperez0111!

I'm excited to give the fixes in `2.5.0-beta.5` a try but unfortunately this issue persists in that version and we get errors like the above:

```
[RangeError: Can not convert <listItem(paragraph("yz"))> to a Fragment (looks like multiple versions of prosemirror-model were loaded)]
```


**`yarn why prosemirror-model` output:**

```
=> Found "prosemirror-model@1.21.1"
info Has been hoisted to "prosemirror-model"
info Reasons this module exists
   - Hoisted from "prosemirror-schema-list#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-commands#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-gapcursor#prosemirror-model"
   - Hoisted from "prosemirror-schema-list#prosemirror-state#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-schema-basic#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-markdown#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-view#prosemirror-model"
   - Hoisted from "prosemirror-schema-list#prosemirror-transform#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-tables#prosemirror-model"
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
=> Found "@tiptap/pm#prosemirror-model@1.21.0"
info This module exists because "@tiptap#pm" depends on it.
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
```

**Comment by nperez0111** [comment]
I'm still waiting on a fix from prosemirror, can you just pin the dep for now to one version & see if things work for you?

**Comment by Nantris** [comment]
Thanks for your reply @nperez0111. I am indeed trying now with the resolutions set. I think that we're describing two separate issues with the `prosemirror-model` though. In my case, it's that there's the two versions, but in your issue it's a bug in `prosemirror-model@1.21.1` itself, even when it's the only version loaded, right?

I'm not really clear on why `prosemirror-schema-list` is loading `1.21.0` instead of `1.21.1` given its specified dependency range: https://github.com/ProseMirror/prosemirror-schema-list/blob/79b62755a061869e0dfa1e877b5033f341dc0592/package.json#L27

PS: All 276 of our tests passed with `prosemirror-model@1.21.1` as the only version installed. It's entirely possible that none of our tests would produce the issue in https://github.com/ProseMirror/prosemirror/issues/1473 - but it would be a bit surprising. Does that bug only affect JSON-output? I'd imagine it would affect HTML output as well (which is what we use.)

**Comment by nperez0111** [comment]
You may not be hitting it if you don't use the "style" tag for parsing HTML which is where we running into issues in our tests for example in this extension: https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/extension-underline/src/underline.ts#L52-L56


So Tiptap cannot upgrade to `prosemirror-model@1.21.1` since it breaks other users who may be relying on that functionality. So I attempted to specify in the @tiptap/pm package that it should only use `prosemirror-model@1.21.0` but because `prosemirror-schema-list` is separately depending on `prosemirror-model` https://github.com/ProseMirror/prosemirror-schema-list/blob/master/package.json#L27 it seems to be trying to resolve that dependency independently of what we specified it as: https://github.com/ueberdosis/tiptap/blob/0e96a2c35e7ccd83c055cbbf9eaf8c71d03cdf13/packages/pm/package.json#L139

Dependency resolution can be difficult & it is unfortunate that there isn't much that we can do in this situation. I hope that @marijnh can get to it at some point. A patch release should not break users.

**Comment by nperez0111** [comment]
@Nantris Happy to hear that all of your tests passed though!

**Comment by Nantris** [comment]
I should have studied that issue more closely - indeed we do not use inline styles. It does seem your hands are tied here.  Hopefully @marijnh can advise on a resolution.

Using Yarn's resolutions is fine as a short-term workaround but becomes hairy when you then need to consume that package in another project.

Even so, I'm thinking it might be advisable to not pin the `prosemirror-model` version in TipTap. When the version is pinned, everyone ends up with two versions of `prosemirror-model` and then has to use a workaround (eg pin dependencies) whereas if `prosemirror-model` is allowed to go to `1.21.1` then only those who depend on inline styles need the workaround. Neither is ideal, but the former theoretically breaks the project for everyone (or maybe just everyone who uses lists?) It seems like a larger cross-section if I had to guess (but I'm also biased because this would simplify my life!) Just my two cents.

**Comment by nperez0111** [comment]
Yea I was just trying to make my life easier so we still have green tests. 

I'll need to look more into it but I'm unsure whether or not this would break others.

**Comment by nperez0111** [comment]
Hopefully resolved with:  v2.5.0-beta.6 now that the issue is resolved upstream

I did have to do a bunch of package lock changes afterward so let me know if there is anything wrong & I can re-release another ontop of it

**Comment by Nantris** [comment]
I'm sorry to report that the issue persists with `2.5.0-beta.6`, although the two versions it installs have changed:

```
❯ yarn why prosemirror-model
yarn why v1.22.22
[1/4] Why do we have the module "prosemirror-model"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "prosemirror-model@1.21.1"
info Has been hoisted to "prosemirror-model"
info Reasons this module exists
   - Hoisted from "prosemirror-schema-list#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-commands#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-gapcursor#prosemirror-model"
   - Hoisted from "prosemirror-schema-list#prosemirror-state#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-schema-basic#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-markdown#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-view#prosemirror-model"
   - Hoisted from "prosemirror-schema-list#prosemirror-transform#prosemirror-model"
   - Hoisted from "@tiptap#pm#prosemirror-tables#prosemirror-model"
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
=> Found "@tiptap/pm#prosemirror-model@1.21.3"
info This module exists because "@tiptap#pm" depends on it.
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
=> Found "@tiptap/pm#prosemirror-schema-list#prosemirror-model@1.21.1"
info This module exists because "@tiptap#pm#prosemirror-schema-list" depends on it.
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "604KB"
info Disk size with transitive dependencies: "604KB"
info Number of shared dependencies: 1
Done in 0.43s.
```

**Comment by Nantris** [comment]
For reference, the relevant portion of our `package.json`:

```js
 "@tiptap/core": "~2.5.0-beta.6",
 "@tiptap/extension-blockquote": "~2.5.0-beta.6",
 "@tiptap/extension-bold": "~2.5.0-beta.6",
 "@tiptap/extension-bullet-list": "~2.5.0-beta.6",
 "@tiptap/extension-code": "~2.5.0-beta.6",
 "@tiptap/extension-code-block": "~2.5.0-beta.6",
 "@tiptap/extension-document": "~2.5.0-beta.6",
 "@tiptap/extension-dropcursor": "~2.5.0-beta.6",
 "@tiptap/extension-floating-menu": "~2.5.0-beta.6",
 "@tiptap/extension-focus": "~2.5.0-beta.6",
 "@tiptap/extension-heading": "~2.5.0-beta.6",
 "@tiptap/extension-highlight": "~2.5.0-beta.6",
 "@tiptap/extension-history": "~2.5.0-beta.6",
 "@tiptap/extension-horizontal-rule": "~2.5.0-beta.6",
 "@tiptap/extension-image": "~2.5.0-beta.6",
 "@tiptap/extension-italic": "~2.5.0-beta.6",
 "@tiptap/extension-link": "~2.5.0-beta.6",
 "@tiptap/extension-list-item": "~2.5.0-beta.6",
 "@tiptap/extension-mention": "~2.5.0-beta.6",
 "@tiptap/extension-ordered-list": "~2.5.0-beta.6",
 "@tiptap/extension-paragraph": "~2.5.0-beta.6",
 "@tiptap/extension-placeholder": "~2.5.0-beta.6",
 "@tiptap/extension-strike": "~2.5.0-beta.6",
 "@tiptap/extension-task-item": "~2.5.0-beta.6",
 "@tiptap/extension-task-list": "~2.5.0-beta.6",
 "@tiptap/extension-text": "~2.5.0-beta.6",
 "@tiptap/extension-typography": "~2.5.0-beta.6",
 "@tiptap/extension-underline": "~2.5.0-beta.6",
 "@tiptap/pm": "~2.5.0-beta.6",
 "@tiptap/react": "~2.5.0-beta.6",
 "@tiptap/suggestion": "~2.5.0-beta.6",
 ```

**Comment by nperez0111** [comment]
Can you check this again, there have been several releases on top of that version now.

This can't possibly be an issue with tiptap anymore because it is specifying a version range that should work now. So now this squarely an issue with your package-lock and just needs to be upgraded or regenerated

**Comment by Nantris** [comment]
Looks good in `2.5.0-pre.13` after running `yarn upgrade`. Not sure what version fixed this and it could have been already fixed when I last reported, in which case I apologize for the wasted time.

Thank you for the continued great work @nperez0111!
