### ISSUE TITLE
[Bug]: InputRules seem not to fire in 2.5.5

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5384]
### Affected Packages

core

### Version(s)

2.5.5

### Bug Description

After upgrading from `2.5.4` to `2.5.5` several tests broke here. I took a look and it seems breakpoints inside of input rules are no longer being hit. Presumably it's not all input rules since only a few tests broke. Most of the broken tests seem to relate to lists.

Example input rule which no longer applies:

```js
wrappingInputRule({
  find: taskItemRegex,
  type: this.type,
  getAttributes: match => ({
    checked: match.at(-1)?.toLowerCase() === 'x',
  }),
}),
```

### Browser Used

Chrome

### Expected Behavior

InputRule behavior is unchanged from `2.5.4`

### Additional Context (Optional)

We have a custom `parseHTML` so it seems unlikely to me that this PR broke it: https://github.com/ueberdosis/tiptap/commit/b47df57444204cd304ea7ae180c68585224df47e

At the same time, none of the others jump out to me as obvious causes either.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
@Nantris I don't see anything that would be different here for input rules between these versions: https://github.com/ueberdosis/tiptap/compare/%40tiptap/vue-3%402.5.4...v2.5.5

2.5.5 was mostly around [vue 3 performance updates](https://github.com/ueberdosis/tiptap/pull/5373), are you using vue-3? 

The only other code change could have been: https://github.com/ueberdosis/tiptap/pull/5321

I would need more information to help you out here

**Comment by nperez0111** [comment]
Is it just the one input rule that is not applying? Could your parseHTML not be applying? Maybe you have the task list extension installed twice? I don't know what could be breaking you here

**Comment by nperez0111** [comment]
Any update on this @Nantris? I've also addressed a couple more bugs since so may be worth upgrading

**Comment by Nantris** [comment]
@nperez0111 thanks for the ping on this.

I tried `2.5.7` but the issue persisted. I was able to identify the problem commit as [4cca3826950176b6d9981cdc6e1e9b654f696319](https://github.com/ueberdosis/tiptap/commit/4cca3826950176b6d9981cdc6e1e9b654f696319#diff-419d346750c8552f050b4af540878e1c6000a9b3f5f7c9f19dca2c8c52d30868) but heck if I know why.

None of the affected rules seem to have anything to do with `atom` nodes. Unfortunately I'm finding it impossible to set breakpoints or logpoints in the `.ts` files, maybe due to some problem in the sourcemaps, so I can't readily provide as much information as I'd like (eg why this is making any difference in a document without any atom nodes present.) 

Via manually editing the file in `node_modules` I was able to at least determine the behavior difference:

- **`2.5.5` (Problem):** `{textBefore: '[x]abc'}`
- **`2.5.4` (No problem):** `{textBefore: '[x]'}`

In both cases the caret was in the position immediately after the `[x]|` (pipe character representing caret)

Thanks again for the great work you're doing @nperez0111!

**Comment by nperez0111** [comment]
Thanks for hunting this down @Nantris  I found the bug & will be resolved by: https://github.com/ueberdosis/tiptap/pull/5407

**Comment by nperez0111** [comment]
Should be resolved already with v2.5.9

**Comment by Nantris** [comment]
Confirmed resolved; forgot to close. Thanks for your great work @nperez0111!
