### ISSUE TITLE
peer dependency prosemirror-tables warning

### ISSUE THREAD

**Issue by jermitval** [ueberdosis/tiptap#555]
When installing with npm, throws the following warning:
```
npm WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 
but none is installed. You must install peer dependencies yourself.
```
Do I need to install prosemirror-tables@^0.9.1 as waring?or just a bug?

**Comment by oshell** [comment]
I have the same problem

**Comment by Peter-Krebs** [comment]
This happens for `prosemirror-tables@1.0.0` as well. Example output (truncated)
```bash
├─┬ tiptap@1.26.6
└─┬ tiptap-extensions@1.28.6
  ├── UNMET PEER DEPENDENCY prosemirror-tables@1.0.0

npm WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 but none was installed.
```

There is an open issue ([Update prosemirror-tables to 1.0.0](https://github.com/atlassian/prosemirror-utils/issues/85)) at `prosemirror-utils` to address this problem.

**Comment by Peter-Krebs** [comment]
Corrected in tiptap@1.26.7, tiptap-extensions@1.28.7
https://github.com/scrumpy/tiptap/issues/305#issuecomment-607412176 (also applies to npm install)

**Comment by waaronking** [comment]
I'm still getting this warning on tiptap@1.27.1 (with tiptap-extensions@1.29.1). Is there something we need to do, or is this something prosemirror needs to worry about?

**Comment by Tumulte** [comment]
Same issue as @waaronking here

**Comment by hanspagel** [comment]
There is nothing we can do about that, `prosemirror-utils` needs to upgrade the `prosemirror-tables` dependency. Here is the related PR over there:
https://github.com/atlassian/prosemirror-utils/pull/93
