### ISSUE TITLE
When pasting markdown, headings don't get converted

### ISSUE THREAD

**Issue by joelearn** [ueberdosis/tiptap#6713]
### Affected Packages

core

### Version(s)

3.0.7

### Bug Description

When pasting some markdown into the editor, the headings remain in markdown format. To recreate, copy the following:
```markdown
## Hi there

This is a _basic_ example of **Tiptap**.
```
and paste into https://tiptap.dev/docs/examples/basics/default-text-editor

You will see `## Hi there` remains as markdown.

### Browser Used

Chrome

### Expected Behavior

Pasting markdown headings should change them to their respective HTML heading elements. For example `## Hi there` should convert to `<h2>Hi there</h2>`.

### Dependency Updates

- [x] Yes, I've updated all my dependencies.

**Comment by andrictham** [comment]
It's not just headings, I don't think any Markdown syntax gets converted at all on paste. Given Markdown support seems to be on the slate of v3 updates, I wonder if the team will do something to improve this.

**Comment by Juethro** [comment]
> It's not just headings, I don't think any Markdown syntax gets converted at all on paste. Given Markdown support seems to be on the slate of v3 updates, I wonder if the team will do something to improve this.

What do you mean? if you paste `**this is bold**` in [https://tiptap.dev/docs/examples/basics/markdown-shortcuts](https://tiptap.dev/docs/examples/basics/markdown-shortcuts) demo editor you will get bold text. From my investigation, I found this:

These few syntax that will work:
- bold (with ** or __)
- italic (with _)
- strikethrough (with ~~)
- highlight code (with `)
- highlight text (with ==)
- link (just copy the url)

paste doesn't work:
- headings
- numbered list
- bullet list (with +, -, *)
- bold and italic (with ***)
- blockquotes (with >)

I don't know about others

By the way, this feature can be turned off by give `false` value on `onPasteRules` in editor. You can see it here [https://tiptap.dev/docs/editor/api/editor#enablepasterules](https://tiptap.dev/docs/editor/api/editor#enablepasterules)
```
import { Editor } from '@tiptap/core'
import StarterKit from '@tiptap/starter-kit'

new Editor({
  content: `<p>Example Text</p>`,
  extensions: [StarterKit],
  enablePasteRules: false,
})
```

**Comment by cactusanil** [comment]
Any update on this. Its not working even after enablePasteRules: false/true.

**Comment by nperez0111** [comment]
This is not supported yet in Tiptap, as stated before.

Those few rules work because of how it is able to parse some elements, but this is mostly coincidentally, not that it fully supports markdown.

**Comment by paulnaber** [comment]
Any updates yet?
Would love to use the native markdown extension.
We currently still use the "aguingand/tiptap-markdown" extension because of this issue.

underline is also something that is not converted on paste by the way

**Comment by Tsuk1ko** [comment]
Here I implemented a `MarkdownClipboard` extension compatible with the official Markdown plugin, based on [the implementation in `aguingand/tiptap-markdown`](https://github.com/aguingand/tiptap-markdown/blob/main/src/extensions/tiptap/clipboard.js).

It should basically achieve the same effect .

```ts
import { Extension } from '@tiptap/core';
import { Plugin, PluginKey } from '@tiptap/pm/state';
import { Slice } from '@tiptap/pm/model';

export const MarkdownClipboard = Extension.create({
  name: 'markdownClipboard',

  addOptions: () => ({
    transformPastedText: true,
    transformCopiedText: true,
  }),

  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey('markdownClipboard'),
        props: {
          clipboardTextParser: (text, _context, plainText) => {
            if (plainText || !this.options.transformPastedText || !this.editor.markdown) {
              return null as any;
            }
            const parsedJson = this.editor.markdown.parse(text);
            const doc = this.editor.schema.nodeFromJSON(parsedJson);
            return new Slice(doc.content, 1, 1);
          },

          clipboardTextSerializer: (slice) => {
            if (!this.options.transformCopiedText || !this.editor.markdown) {
              return null as any;
            }
            const sliceJson = slice.toJSON();
            sliceJson.type = 'doc';
            const md = this.editor.markdown.serialize(sliceJson);
            return md.replace(/(?:\n|^)&nbsp;(?:\n|$)/g, '');
          },
        },
      }),
    ];
  },
});
```

**Comment by cactusanil** [comment]
I have copied markdown content and paste in editor. Its still not converting even after using your provided extension.

**Comment by Tsuk1ko** [comment]
> I have copied markdown content and paste in editor. Its still not converting even after using your provided extension.

Ensure the content you paste is **plain text**.

You can inspect your clipboard content using this tool: https://evercoder.github.io/clipboard-inspector/

You need to ensure that the clipboard contains only `text/plain` and not `text/html`.

If `text/html` exists, the HTML content will be used for pasting, which is consistent with the behavior of `aguingand/tiptap-markdown`. HTML pasting won't trigger `clipboardTextParser` hook.

Typically, if you copy from plain text environments like Notepad or VSCode (with language mode set to `plaintext`), the text will only contain `text/plain`. If you copy from web pages or Microsoft Word, the text will include `text/html`.

**Comment by coEraldoEnergy** [comment]
Many places I use to copy text (including vscode) copy more than just plain text and the pasted result unfortunately is not interpreted markdown. Would also like to have the option to interpret pasted markdown as parsed markdown.

If I paste plain text only (via CMD+SHIFT+V) it currently gets interpreted as plain text instead of parsed as markdown.

**Comment by zargham-k** [comment]
pasting a markdown (plain text) from an agentic source into editor is now common reality, would be great to have markdown paste supported natively.
