### ISSUE TITLE
Can't unmount vue3 editor in test without causing an error

### ISSUE THREAD

**Issue by eriknygren** [ueberdosis/tiptap#6777]
### Affected Packages

core, vue

### Version(s)

3.0.9

### Bug Description

So in my vitest run of my tiptap editor, either with jsdom or happy-dom I get this when trying to unmount my tiptap editor component

```
TypeError: _a.remove is not a function
 ❯ Editor.unmount ../../node_modules/@tiptap/core/src/Editor.ts:185:15
 ❯ Editor.destroy ../../node_modules/@tiptap/core/src/Editor.ts:713:10
 ❯ ../../node_modules/@tiptap/vue-3/src/useEditor.ts:20:19
 ❯ ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2818:40
 ❯ callWithErrorHandling ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:200:19
 ❯ callWithAsyncErrorHandling ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:207:17
 ❯ Array.hook.__weh.hook.__weh ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2798:19
 ❯ Object.invokeArrayFns ../../node_modules/@vue/shared/dist/shared.cjs.js:90:11
     88| const invokeArrayFns = (fns, ...arg) => {
     89|   for (let i = 0; i < fns.length; i++) {
     90|     fns[i](...arg);
       |           ^
     91|   }
     92| };
 ❯ unmountComponent ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5929:14
 ❯ unmount ../../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5819:7
```

I haven't been able to isolate it in a repo as I can't recreate it without my extensions. However I don't think they are doing anything out of the ordinary.

But it seems to be pointing quite specificall to [this line](https://github.com/ueberdosis/tiptap/blob/224cb2c77a7921e62b18f4b510bb314b582926df/packages/core/src/Editor.ts#L185)

Which seems [to point to this specific PR](https://github.com/ueberdosis/tiptap/pull/6182)

Previously I was on version `2.9.1` where this was not an issue, which I believe was before this change.

I know this is not lots of info to go on, but maybe it's obvious to those who made this change? so CCing @nperez0111 and @bdbch for that reason.

Thanks in advance, any advice is highly appreciated 🙏 

### Browser Used

Other

### Expected Behavior

The component can happily unmount in vue-test-utils without throwing an error

### Dependency Updates

- [x] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
The private variable is initialized to null when it should initialized to undefined. At least to respect the ?. 

Make a PR to fix it. I don't work at Tiptap anymore

**Comment by eriknygren** [comment]
Thanks @nperez0111, however I don't think switching undefined to null will fix it. I believe the `?` operator will operate in the same way with those two values. I think `css` is being set to something that's not expected

<img width="807" height="266" alt="Image" src="https://github.com/user-attachments/assets/927db352-9698-4492-a764-6c34d94e89f8" />

So I'll patch this like:
```ts
    if (this.css && typeof this.css.remove === 'function') {
      this.css.remove()
    }
 ```

[added a PR ](https://github.com/ueberdosis/tiptap/pull/6781), thanks for your input!

**Comment by bdbch** [comment]
Should be fixed with 3.1.0

**Comment by eriknygren** [comment]
I don't think it's fixed, neither of the related PRs were merged? can still be reproduced in 3.1.0
