### ISSUE TITLE
Text of Mention Node isn’t copied as Plain Text

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/tiptap#858]
Take a look at this example: https://tiptap.dev/suggestions

If you select and copy the second paragraph ("This is an example how to mention...") and then paste it anywhere that isn't TipTap, it will copy the following: 

"This is an example how to mention some users like  or . Try to type @ and a popup (rendered with tippy.js) will appear. You can navigate with arrow keys through a list of suggestions."

Notice it doesn't copy `@Philip Kuhn` or `@Hans Pagel`.

Is there a value property or anything I'm missing with making sure a custom node can have a text value that can be copied? Or is this a ProseMirror issue?

_Originally posted by @zawilliams in https://github.com/ueberdosis/tiptap/discussions/857_

**Comment by hanspagel** [comment]
Thanks for reporting @zawilliams! That’s a tough one.

The text copied is HTML so it works to paste the text (including the text of the mention) e. g. to Slack (supports pasting HTML), but not VS Code (uses plain text).

It’s related to the schema of the Mention, to be more precise to the inline configuration:
https://github.com/ueberdosis/tiptap/blob/67d25bf36b05bdc81d782b06f1002416b4532cbb/packages/tiptap-extensions/src/nodes/Mention.js#L29-L30

I tried to fiddle around with that, but couldn’t find a solution. I still not fully understand the issue, but this seems very related:
https://github.com/ProseMirror/prosemirror/issues/114
https://discuss.prosemirror.net/t/discussion-inline-nodes-with-content/496/4

If I get this all right, it’s hard to change that behaviour. If anyone has an idea, I’m very thankful for help!

**Comment by Priestch** [comment]
@hanspagel Fix this issue in GH-860, it seems work!

**Comment by hanspagel** [comment]
Wow, thanks @Priestch! Fixed with #860.

@zawilliams would you mind to update tiptap-extensions to the latest version and try again?

**Comment by zawilliams** [comment]
Hey @hanspagel - I just updated things and ran the same example code at https://github.com/ueberdosis/tiptap/blob/main/examples/Components/Routes/Suggestions/index.vue and I still can't copy and paste the `@mention` text from TipTap into something like the browser bar or VS Code. Just appears as a space when pasting.

**Comment by zawilliams** [comment]
Actually, I'm not even sure it's a space that registers in place of the `@mention` - I think that's just the space before or after that gets appended.

**Comment by zawilliams** [comment]
@hanspagel @Priestch I made a reproduction so you can see what is happening even with the latest `tiptap-extensions` version: https://codesandbox.io/s/vue-tiptap-forked-5wy7y?file=/src/views/Home.vue

Press the "Add Mention" button and then select all, then copy and paste the text into your browser bar or VS Code and you'd expect to use the `@mention` text included, but it isn't.

**Comment by Priestch** [comment]
@hanspagel @zawilliams Try to fix in GH-861, maybe the key point is the content must not be left empty.

**Comment by zawilliams** [comment]
@Priestch this does seem to fix the issue. Thanks for looking into this!

**Comment by hanspagel** [comment]
I think that’s fixed now. 🙌 Thanks @Priestch for your work on this! 💖
