### ISSUE TITLE
Space (whitespace) gets deleted after pressing any other key

### ISSUE THREAD

**Issue by obsessen** [ueberdosis/tiptap#873]
**Describe the bug**
Space gets deleted after pressing any other key.

**Steps to Reproduce / Codesandbox Example**
1. In an empty editor put eg. "abc"
2. Press the spacebar
3. Press eg. "d"

**Expected behavior**
Whitespace should not get deleted

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2692737/97013768-bc3f6800-1549-11eb-8ba1-e192f5ce5981.gif)

This is with the most barebones include of the editor and it still doesn't work for me.

**Environment**
 - Version 1.30.0

**Comment by glavdir** [comment]
I fixed this bug in my project by next code:

`
.my-editor >>> .ProseMirror{
 white-space: normal;
  word-break: break-word;
}`

**Comment by obsessen** [comment]
Thank you for your suggestion @glavdir, but this didn't work for me.

I'm looking at the Vue dev tools and the editor value (by getHTML()) looks like this after pressing the spacebar:
`"<p>abc </p>"`
and after presing another key:
`"<p>abcd</p>"`

**Comment by hisem** [comment]
Hi @obsessen,

I was having the exact same problem, and found #168 which helped me solve the problem.

You can pass the following option to the Editor constructor:
```
new Editor({
[...]
    parseOptions: {
        preserveWhitespace: true
    }
[...]
});
```

Hope this helps!

**Comment by obsessen** [comment]
Hello @hisem,

yes, I saw that issue and tried the suggested fix but for me, the issue still persists.

I also tried the 'full' option for the preserveWhitespace with no improvement.

**Comment by Tilesto** [comment]
> Hello @hisem,
> 
> yes, I saw that issue and tried the suggested fix but for me, the issue still persists.
> 
> I also tried the 'full' option for the preserveWhitespace with no improvement.
> 
> **Edit:**
> I ended up fixing the issue with the combination of your suggestions with a little twist. So thank you @hisem and @glavdir.
> 
> To anyone who ends up here with the same problem here is the solution:
> 
> ```
> .ProseMirror * {
>   white-space: pre-wrap;
>   word-wrap: break-word;
> }
> ```
> 
> and add this to the Editor options object for good measure (the CSS should be enough by itself):
> 
> ```
> new Editor({
>   ...
>   parseOptions: 
>       preserveWhitespace: 'full'
>   }
>   ...
> });
> ```

preserveWhitespace: 'full' - really works for me! But "true" - not working.
Thanks a lot!

**Comment by rosnaib11** [comment]
I'm using react tiptap latest version as of now. This is not working for me

**Comment by JahnoelRondon** [comment]
### React solution using tiptaps content options

Yeah no this is the actual solution when setting content. You just have to use the options parameter and set the  white spaces.

```js
   editor.commands.setContent(cleanText, false, {preserveWhitespace: "full"});
```

**Comment by szymekjanaczek** [comment]
Unfortunately, I've found another problem.
Let's consider text like below:
```html
<h1>My test heeader</h1>
<p>This is my test <em>paragraph <strong>with</strong></em> <strong>text</strong></p>
```

While trying to set it as content - even using code from @JahnoelRondon (thanks!), TipTap shows it in this way:
<img width="452" alt="Screenshot 2024-01-16 at 15 32 35" src="https://github.com/ueberdosis/tiptap/assets/74879123/d35c124d-3f84-42cd-a3f7-5d67734d8264">

It looks like TipTap trims spaces anyway.

**Comment by szymekjanaczek** [comment]
Unfortunately, I've found another problem.
Let's consider text like below:
```html
<h1>My test heeader</h1>
<p>This is my test <em>paragraph <strong>with</strong></em> <strong>text</strong></p>
```

While trying to set it as content - even using code from @JahnoelRondon (thanks!), TipTap shows it in this way:
<img width="452" alt="Screenshot 2024-01-16 at 15 32 35" src="https://github.com/ueberdosis/tiptap/assets/74879123/d35c124d-3f84-42cd-a3f7-5d67734d8264">

It looks like TipTap trims spaces anyway.

**Comment by krokhale** [comment]
This worked for me:

`   editor.commands.setContent(cleanText, false, {preserveWhitespace: "full"});`

Also, it seems like one can add a line break using shift + enter.

**Comment by nsch0e** [comment]
@szymekjanaczek I recently also had the same problem and I just updated all tiptap related packages to the most recent version (2.2.4) and for me the spaces between tags now stay.

**Comment by szymekjanaczek** [comment]
@nsch0e, yep - it was fixed in #4792, and now works correctly ;). But thanks anyway!

**Comment by miketalley** [comment]
I'm still seeing this issue in Firefox (125.0.2 (64-bit)) using @tiptap v2.3.0.
```
    "@tiptap/extension-floating-menu": "^2.3.0",
    "@tiptap/extension-table": "^2.3.0",
    "@tiptap/extension-table-cell": "^2.3.0",
    "@tiptap/extension-table-header": "^2.3.0",
    "@tiptap/extension-table-row": "^2.3.0",
    "@tiptap/extension-underline": "^2.3.0",
    "@tiptap/pm": "^2.3.0",
    "@tiptap/starter-kit": "^2.3.0",
    "@tiptap/vue-3": "^2.3.0",
```

**Comment by poplevente** [comment]
same for me. i have the same issue and the proposed fixed don't work anymore. Anyone else having the same? i think the bug needs to be reopened. any other solution that we could try?

**Comment by Surajk7725** [comment]
Use this bro in the useEffect like this 

useEffect(() => {
    if (editor) {
      editor.commands.setContent(cleanedText, false, {preserveWhitespace: "full"});
    }
  }, [content, editor]);
  
  if you are using content to save it in a document then use like this docx.content

**Comment by jittarao** [comment]
> ### React solution using tiptaps content options
> Yeah no this is the actual solution when setting content. You just have to use the options parameter and set the white spaces. they are false by default so you need to set it to true however if you want all spaces to pass then "full" is the better bet.
> 
> ```js
>    editor.commands.setContent(cleanText, false, {preserveWhitespace: "full"});
> ```

This solution worked for me. Thanks!

**Comment by GondarMD** [comment]
> This worked for me:
> 
> ` editor.commands.setContent(cleanText, false, {preserveWhitespace: "full"});`
> 
> Also, it seems like one can add a line break using shift + enter.

This worked for me with a Vue 3 app using the "Gutentap" editor (https://github.com/johnpuddephatt/gutentap/tree/main), implemented with TipTap.

**Comment by looping67** [comment]
> I'm using react tiptap latest version as of now. All solutions above not working for me
> 
> ![image](https://user-images.githubusercontent.com/26837762/160398620-80a6f005-924c-447e-a8b0-01e3bba92b50.png)
> 
> ```
> react
>   const edtor = useEditor({
>     content,
>     extensions,
>     editable,
>     parseOptions: {
>       preserveWhitespace: 'full',
>     },
>     onUpdate: async ({ editor }) => {
>       setEditorHtmlContent(editor.getHTML())
>     },
>   })
>   
>   useEffect(() => {
>     console.log(projectDescription)
>     if (!edtor?.isDestroyed) {
>        edtor?.commands.setContent(projectDescription, false)
>     }
>   }, [projectDescription])
> 
> 
> css
> .ProseMirror * {
>   white-space: pre-wrap !important;
>   word-wrap: break-word !important;
> }
> ```
`preserveWhitespace: 'full',` it works for me

**Comment by chasemcdo** [comment]
I am still running into this issue when re-loading the Editor content from saved text (from `editor.getText`). Specifically if my first action within the editor is anything other than adding a newline using `return` (on Mac), then all newlines get removed.

My flow is as follows:
- user enter stuffs into editor
- content is saved in its text format
- saved text is loaded into the content
- user can edit and resave content (this is where I am having issues)

Has anyone discovered a fix for this or do I need to be reloading from`getHTML`? I am using `getText`, since the text is used such that we don't need/want the HTML content within it. (ie if we reload from `getHTML` we will still be saving `getText`)

https://github.com/user-attachments/assets/a2e99124-b376-4614-8232-46adcece1935

**Comment by chasemcdo** [comment]
Found a solution for my above issue. If you're using more complex formatting you'll likely want to simply use the `getHTML` function as seems to be the recommended method, but for my purpose (and maybe anyone looking at this in the future), I chose to _hydrate_ the text on load.

ie replacing newlines with linebreaks via something like `content.replace(/\n/g, "<br />")` with a similar process for hydrating mentions.

Note that this requires the [hardbreak extension](https://tiptap.dev/docs/editor/extensions/nodes/hard-break) and the use of `blockSeparator: "\n"` or else you'll find that extra newlines get inserted when saving (another reason why using HTML directly would be preferable for most use cases).
